#!/usr/bin/env bash

yabai -m config layout                       bsp

yabai -m config window_opacity               off
yabai -m config window_shadow                on

yabai -m config window_animation_duration    0.0
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child


yabai -m config window_topmost               on

yabai -m config top_padding                  50
yabai -m config bottom_padding               20
yabai -m config left_padding                 30
yabai -m config right_padding                30
yabai -m config window_gap                   25

yabai -m config focus_follows_mouse          lazy
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize


yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add subrole="^AXFlexibleWindow$" manage=off

yabai -m signal --add event=window_focused action="sketchybar --trigger update_windows"
yabai -m signal --add event=window_created action="sketchybar --trigger update_windows"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger update_windows"

echo "yabai configuration loaded.."
